### ISSUE TITLE
Levantamento de Requisitos

### ISSUE THREAD

**Issue by nibiroo** [Professor-Dudarts/ludus_service_standings#25]
Documentar os Requisitos Funcionais e Não-Funcionais para atender à necessidade do sistema

**Comment by nibiroo** [comment]
Documentar os Requisitos Funcionais e Não-Funcionais para atender à necessidade do sistema

**Comment by nibiroo** [comment]
[ludus_service_standings-issues-25.pdf](https://github.com/Professor-Dudarts/ludus_service_standings/files/10949951/ludus_service_standings-issues-25.pdf)

**Comment by nibiroo** [comment]
[ludus_service_standings-issues-25.pdf](https://github.com/Professor-Dudarts/ludus_service_standings/files/10949953/ludus_service_standings-issues-25.pdf)

**Comment by nibiroo** [comment]
Nos requisitos funcionais, foi necessário acrescentar que trata-se de dois tipos de campeonatos, sendo eles pontos corridos e fases de grupos.


[ludus_service_standings-issues-25.pdf](https://github.com/Professor-Dudarts/ludus_service_standings/files/10951843/ludus_service_standings-issues-25.pdf)


@PPedrosouza, favor revisar e caso esteja certo, pode dar close na issue e colocar como Done.

**Comment by PPedrosouza** [comment]
@nibiroo 
Nos requisitos não funcionais seria interessante termos as definições da linguagem, banco e usabilidade já definidas.

**Comment by nibiroo** [comment]
Acho que isso deve ser descrito na documentação de Arquitetura do Sistema, não?

Porque naquela documentação vou descrever quais linguagens, banco e o motivo de eu escolher elas.

Quando você fala de usabilidade, seria o que? Como?

**Comment by PPedrosouza** [comment]
É verdade, faria mais sentido estar nessa documentação de arquitetura.
Sobre a usabilidade seria a necessidade do usuário. Seria mais fácil de entender com a ajuda de um protótipo no Figma ou outra ferramenta. Mas por hora vamos deixar para o outro documento.

**Comment by nibiroo** [comment]
@dudarts, fique a vontade para visualizar e dar feedbacks.
