### ISSUE TITLE
Documento de Caso de Uso

### ISSUE THREAD

**Issue by nibiroo** [Professor-Dudarts/ludus_service_standings#26]
Baseados nos requisitos funcionais, modelar o diagrama de caso de uso, preferencialmente no draw.io

**Comment by nibiroo** [comment]
[ludus_service_standings-issues-26.pdf](https://github.com/Professor-Dudarts/ludus_service_standings/files/10950022/ludus_service_standings-issues-26.pdf)

**Comment by nibiroo** [comment]
Foi necessário refazer a documentação de caso de uso.

[ludus_service_standings-issues-26.pdf](https://github.com/Professor-Dudarts/ludus_service_standings/files/10952566/ludus_service_standings-issues-26.pdf)

@PPedrosouza, favor revisar e caso esteja certo, pode dar close na issue e colocar como Done.

**Comment by nibiroo** [comment]
LEVAR EM CONSIDERAÇÃO PARA MVP, SOMENTE CAMPEONATO DE PONTOS CORRIDOS (BRASILEIRÃO)

**Comment by PPedrosouza** [comment]
Revisado!

**Comment by nibiroo** [comment]
@dudarts, fique a vontade para visualizar e dar feedbacks.
