### ISSUE TITLE
Diagrama de Classe

### ISSUE THREAD

**Issue by nibiroo** [Professor-Dudarts/ludus_service_standings#27]
Baseado nas necessidade dos Casos de Uso, modelar o diagrama de classes, preferencialmente no draw.io

**Comment by nibiroo** [comment]
[ludus_service_standings-issues-27.pdf](https://github.com/Professor-Dudarts/ludus_service_standings/files/10952580/ludus_service_standings-issues-27.pdf)

@PPedrosouza, favor revisar e caso esteja certo, pode dar close na issue e colocar como Done.

**Comment by higorbuueno** [comment]
![Image](https://user-images.githubusercontent.com/82554270/224873712-db8cc08e-ae32-4bac-9480-3a5eb0c7d6b4.png)

**Comment by nibiroo** [comment]
[ludus_service_standings-issues-27.pdf](https://github.com/Professor-Dudarts/ludus_service_standings/files/10993752/ludus_service_standings-issues-27.pdf)

@PPedrosouza, favor revisar e caso esteja certo, pode dar close na issue.

**Comment by PPedrosouza** [comment]
Revisado!

**Comment by nibiroo** [comment]
@dudarts, fique a vontade para visualizar e dar feedbacks.
