### ISSUE TITLE
Arquitetura do Sistema

### ISSUE THREAD

**Issue by nibiroo** [Professor-Dudarts/ludus_service_standings#28]
Baseado nos Requisitos Não-Funcionais, modelar a arquiterura do sistema, justificando a escolha de cada recurso.

**Comment by nibiroo** [comment]
[ludus_service_standings-issues-28.pdf](https://github.com/Professor-Dudarts/ludus_service_standings/files/10953000/ludus_service_standings-issues-28.pdf)

@PPedrosouza , favor revisar e caso esteja certo, pode dar close na issue e colocar como Done.

**Comment by PPedrosouza** [comment]
Revisado!

**Comment by nibiroo** [comment]
@dudarts, fique a vontade para visualizar e dar feedbacks.
